audit_header: false
title: Boston Real Estate Video Blog with Scott Paskerian
description: Our mission at Engel & Völkers is to be your best resource for Boston real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Engel & Völkers, your professional Boston Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Scott Paskerian
  title:
  license_number:
  about_markdown: |
    I am a dedicated real estate advisor with Engel and Voelker's, Boston. I provide exceptional service and up-to-date market information to ensure that my clients make well-informed decisions.  I cover all of Greater Boston and Cambridge for buyers, sellers and investors.  While the thought of buying or selling your home may seem daunting, my goal is to simplify the process for my clients by always being available to answer all questions, and ensure a smooth, professional process from beginning to end.   If you are seeking advise on your future real estate transaction, please don't hesitate to reach out.
  brand: Engel & Völkers
  brokerage:
  market: Boston
  address: 46 Gloucester St.<br>Boston, MA 02115
  phone: 617-678-8603
  phone_type:
  phone2:
  phone2_type:
  email: scott.paskerian@evusa.com
  url: http://www.mybostonliving.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.mybostonliving.com/evaluation
  second_CTA_text: Home Search
  second_CTA_URL: http://www.mybostonliving.com/listing

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Boston Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.mybostonliving.com/evaluation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Boston Home?"
    CTA_text2: "Search the entire MLS for your Boston home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.mybostonliving.com/listing

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/scottpboston/
  linkedin_url: https://www.linkedin.com/in/spaskerian/
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/thebest_of_boston/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Scott-Paskerian/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Boston Real Estate Podcast with Scott Paskerian'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Boston Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Engel & Völkers - your professional Boston Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Boston, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Scott Paskerian'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Boston Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ed1c24'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
